{"name": "测试03用例名称", "status": "passed", "start": 1611064285289, "stop": 1611064285289, "uuid": "f09da398-b89a-4232-9517-8e8f8387bb67", "historyId": "aaeffdda95d4d34ff4d03238f03c8139", "testCaseId": "e69660cb497d57b4d0abb880f6116dec", "fullName": "test_case03#test_03", "labels": [{"name": "story", "value": "用户下单失败的情况"}, {"name": "suite", "value": "test_case03"}, {"name": "host", "value": "DESKTOP-LTNMVII"}, {"name": "thread", "value": "17156-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "test_case03"}]}